eMake Medusa's config map be a merge of MedusaConfig object and clusterr spec
k8ssandra/k8ssandra-operator pull request #1187
Opened 2024-01-25 19:30 UTC by rzvoncek

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #1158.

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2024-01-26 15:26 UTC, adejanovski requested changes
A few minor changes and a **todo:**

We need an e2e test for this.
Modify the `single-dc-encryption-medusa` fixture to add a MedusaConfiguration object and modify the K8ssandraCluster storage properties to replace them with the medusaConfigurationRef.
The medusa-bucket-key will be created already (it's at the root of the `fixtures` directory) so you just need to reference it in the MedusaConfiguration object.

2024-01-29 09:52 UTC, rzvoncek commented on apis/k8ssandra/v1alpha1/k8ssandracluster_webhook.go
> +	ErrNoStoragePrefix = fmt.Errorf("medusa storage prefix must be set")
Ammended into the initial commit.

2024-01-29 09:54 UTC, rzvoncek commented on controllers/k8ssandra/medusa_reconciler.go
> +		desiredKc := kc.DeepCopy()
Ammended into the inital commit.

2024-01-29 09:56 UTC, rzvoncek commented on controllers/k8ssandra/medusa_reconciler_test.go
> +	require.Error(err, "creating a cluster without Medusa's storage prefix should not happen if if the MedusaConfig object exists")
Ammended into an exisitng commit.

2024-01-29 09:57 UTC, rzvoncek commented on docs/content/en/tasks/backup-restore/_index.md
> +      peffix: demo
Ammended into the initial commit.

2024-01-29 15:41 UTC, adejanovski approved these changes

2024-01-29 16:30 UTC, merged