Add the ability to override default registry and set imagePullSecrets
k8ssandra/k8ssandra-operator pull request #1281
Opened 2024-04-12 15:59 UTC by burmanm

… for medusa/reaper/stargate

**What this PR does**:
Adds two new env variables, DEFAULT_REGISTRY which overrides the default registry used to deploy external images and a IMAGE_PULL_SECRETS that allows to set certain imagePullSecrets always.

The Helm chart already had values for these, ``.image.registryOverride`` and ``.imagePullSecrets[]``

Running the following command:

``helm template charts/k8ssandra-operator --api-versions=cert-manager.io/v1 --set 'imagePullSecrets={a,b,c}' --set image.registryOverride=localhost:5001``

Gives us the following deployment:

```yaml
        - name: DEFAULT_REGISTRY
          value: "localhost:5001"
        - name: IMAGE_PULL_SECRETS
          value: "a,b,c"
```

**Which issue(s) this PR fixes**:
Fixes #1280

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2024-04-12 19:25 UTC, olim7t requested changes

2024-04-12 19:25 UTC, olim7t commented on pkg/stargate/deployments.go
> -		Registry:   images.DefaultRegistry,
[issue] I agree that we can remove this, but there is now a problem with the way we handle defaults.

I've created a test environment and manually configured the operator deployment with a wrong registry value:
```yaml
- name: DEFAULT_REGISTRY
  value: localhost:1234
```
Then created a cluster with a Stargate spec that does not specify the image. I would expect this to fail, but it doesn't. It turns out the operator is still pulling Stargate from docker.io.

I think the problem comes from the fact that the `Image` CRD provides a default value for the field:
```go
	// +kubebuilder:default="docker.io"
	// +optional
	Registry string `json:"registry,omitempty"`
```
Therefore when we hit this instruction in `ApplyDefaults()` (same source file)...
```go
	if merged.Registry == "" {
		merged.Registry = DefaultRegistry
	}
```
... `merged.Registry` is "docker.io", and the default is not applied.

I think the solution is to remove the default value in the CRD. I've validated that it solves the problem in my test.

2024-04-15 06:48 UTC, burmanm commented on pkg/images/images.go
> +	secrets = append(secrets, DefaultPullSecretOverride...)
I don't think we've ever had this issue solved (the CollectPullSecrets is an old method). I'll discuss with Alex what's the plan in the use-case we need this.

2024-04-15 07:03 UTC, burmanm commented on pkg/images/images.go
> +	secrets = append(secrets, DefaultPullSecretOverride...)
Apparently this is intended to be handled externally.

2024-04-15 14:32 UTC, olim7t approved these changes
👍 The default is now correctly applied.

2024-04-15 15:19 UTC, merged