Clean up MedusaBackupJobs and propagate MedusaTask labels
k8ssandra/k8ssandra-operator pull request #1339
Opened 2024-05-31 18:47 UTC by c3-clement

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #1334 #1336 

**Checklist**
- [ ] Changes manually tested
- [X] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2024-06-03 12:41 UTC, c3-clement commented
If this PR got merged and approved, I would be happy to forward port those changes to 1.15, 1.16 and main branch.

2024-06-04 09:05 UTC, rzvoncek requested changes
Hello and thanks (again) for the PR!

I gave this a look, including manually testing the changes. Everything worked smoothly 😎 . I'm only requesting changes because of the headline in the changelog.

I had a small trouble testing this after rebasing on top of the current main. Something changed with the manifest generation and the `make manifests` command was throwing  segmentation errors and panics. The sequence of steps I had to do to make it work was:
* `rm` my k8ssandra-operator folder
* clone the repo again
* checkout the branch of this pr
* run `make manifests`
* run `make single-up`

2024-06-04 12:41 UTC, c3-clement commented on CHANGELOG/CHANGELOG-1.14.md
> +## v1.14.1 - 2024-06-03
Updated CHANGELOG.

If this PR get merged, could a 1.14.1 version be released?

2024-06-11 13:32 UTC, rzvoncek approved these changes
Thanks for the changelog update, looks perfect now.

2024-06-11 13:35 UTC, merged

2024-06-11 14:17 UTC, c3-clement commented
> Thanks for the changelog update, looks perfect now.

Thanks for approving and merging @rzvoncek ! 
I have two questions:

1. In addition to main, should we also port this change to release/1.15 and release/1.16? I'll be happy to open PRs.
2. Will a 1.14.1 version be released with this change?