K8OP-295 Expose Medusa's gRPC server port configuration
k8ssandra/k8ssandra-operator pull request #1456
Opened 2024-11-25 15:46 UTC by rzvoncek

**What this PR does**:
This PR allows users of k8ssandra-operator to specify newly-added config field in Medusa that controls which port Medusa will use to start its gRPC server on.

**Which issue(s) this PR fixes**:
Fixes #1455 

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2025-01-03 11:27 UTC, rzvoncek commented
@adejanovski , I've used the Github UI to resolve the merge conflict (it was just a changelog entry). But it now made a merge commit. I'm not sure that's what we want. Please let me know if it's a no-no and I'll redo this, most likely with an entirely new branch into which I'll cherry-pick the relevant commits.

2025-01-06 09:23 UTC, rzvoncek commented
I had to rebase this to resolve another conflict. The merge commit went away, and the CI is green.

2025-01-10 07:44 UTC, adejanovski requested changes
Just one blocking comment on using a multi arch image by default, and one quick refactoring suggestion.

2025-01-10 07:44 UTC, adejanovski commented on pkg/medusa/reconcile.go
> +	DefaultMedusaVersion         = "a1f7647-tmp"
**Todo:** let's use a master multi arch image here, at least until we cut out a release.
```suggestion
	DefaultMedusaVersion         = "97aa0276"
```

2025-01-10 07:44 UTC, adejanovski commented on controllers/medusa/medusatask_controller.go
> +	addr := net.JoinHostPort(pod.Status.PodIP, fmt.Sprint(medusaPort))
**Suggestion:** refactor to avoid code duplication in `GetBackups()` and `doPurge()`

2025-01-13 14:04 UTC, rzvoncek commented on controllers/medusa/medusatask_controller.go
> +	addr := net.JoinHostPort(pod.Status.PodIP, fmt.Sprint(medusaPort))
pushed a commit doing this

2025-01-21 08:38 UTC, merged