Add DC doc
k8ssandra/k8ssandra-operator pull request #439
Opened 2022-02-27 22:35 UTC by jsanda

**What this PR does**:
Provides documentation for adding a DC to an existing cluster

**Which issue(s) this PR fixes**:
Fixes #438

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [x] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2022-03-03 16:06 UTC, jeffbanks requested changes

2022-03-11 18:25 UTC, johnsmartco commented
John @jsanda, this doc is really helpful.  My thought with the current "docs-v2" Tasks section is to start over, replace all the topics currently deployed under https://docs-v2.k8ssandra.io/tasks/ ... (which are merely copies of the "docs-v1" content) ... with individual new/updated task-based topics like the one you wrote in this PR.  Over time, we'll add to the set of task-based articles under https://docs-v2.k8ssandra.io/tasks/<topic>.html.  Might categorize the tasks in doc subfolders when that makes sense.

2022-03-28 22:01 UTC, jsanda commented on docs/add-dc.md
> +## Choose Source Datacenter for Streaming
Good suggestion. I provide some detail.

2022-03-28 22:30 UTC, jeffbanks approved these changes
Looks like just a single misspelling.  Good to go after that!

2022-03-28 22:30 UTC, jeffbanks commented on docs/add-dc.md
> +Next the operator updates the replication strategy of user-defined keyspsaces. The
mispelled keyspaces

2022-03-28 22:39 UTC, merged