Add support for JWT authentication in Stargate
k8ssandra/k8ssandra-operator pull request #558
Opened 2022-06-03 16:42 UTC by adutra

**What this PR does**:
Adds support for JWT authentication in Stargate.

**Which issue(s) this PR fixes**:
Fixes #531.

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2022-06-09 21:22 UTC, adutra commented
I was finally able to add an e2e test. Ready for review.

2022-06-10 13:18 UTC, adutra commented
@caniko would you be able to test this PR with your own setup? Thanks!

2022-06-12 11:48 UTC, caniko commented
> @caniko would you be able to test this PR with your own setup? Thanks!

@adutra, I have been busy with an urgent analysis project. I will test this week. Thank you!

2022-06-13 11:55 UTC, adejanovski approved these changes
LGTM, with just a minor nit on some repeated variables.

2022-06-13 11:55 UTC, adejanovski commented on pkg/stargate/deployments.go
> +		// See https://github.com/stargate/stargate/issues/792 for more.
Awesome comment!

2022-07-05 13:01 UTC, adutra commented
I've rebased and fixed the conflicts. Waiting for the CI runs to finish.

2022-07-06 13:51 UTC, adutra commented
It seems the UpgradeOperatorImage e2e test is broken. I will look into it before merging.

2022-07-06 16:59 UTC, adejanovski commented
> It seems the UpgradeOperatorImage e2e test is broken. I will look into it before merging.

You may want to rebase on top of main. I fixed it there as there were some timing issues with Stargate upgrades.

2022-07-07 08:50 UTC, adejanovski commented on apis/stargate/v1alpha1/stargate_types.go
> -	Auth *bool `json:"auth,omitempty"`
It is, and it seems like it's breaking our upgrade e2e test.

2022-07-07 09:54 UTC, adejanovski requested changes
As pointed out by @jsanda, the change to the Stargate CRD is a breaking one. 
This is what's causing trouble in the upgrade test because the CRDs loaded are the newest but the k8ssandra-operator image is 1.0.0, which then prevents the creation of the Stargate CR with `auth: true`. While this is incorrect and should be done differently, I assume folks would run into troubles during upgrades anyway since there's no converting webhook.
We need to figure out if we want to keep the old auth  setting on top of the newly introduced structure and deal with those in the controller, or bump the api version and add a converting webhook.

2022-07-08 08:46 UTC, adutra commented on apis/stargate/v1alpha1/stargate_types.go
> -	Auth *bool `json:"auth,omitempty"`
I didn't know we cared about breaking changes in v1alpha1. There might be many other breaking changes already between 1.0 and 1.2.

2022-07-08 08:54 UTC, adejanovski commented on apis/stargate/v1alpha1/stargate_types.go
> -	Auth *bool `json:"auth,omitempty"`
I think we should adhere to a policy where breaking changes are supported from one version to the next, using a converting webhook.
As unstable as our APIs can be for now, upgrades should always be possible.
If we follow the [Kubernetes versioning policies](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api), having alpha level APIs mean we can remove them without any prior deprecation, but in our case the problem is slightly different: K8ssandraOperator generates the Stargate resources and should be able to handle any Stargate API change gracefully, including the upgrades.

2022-07-08 09:03 UTC, adutra commented
I reinstated the boolean field. As usual with Kubernetes, the change itself took 5 minutes, and local re-testing took 6 hours. But I expect all tests to pass now. Only for some strange reason, they didn't run on my last commit. I'll kick a manual run.

2022-07-08 12:54 UTC, adutra commented on test/e2e/suite_test.go
> +	interval := 1 * time.Second
Sorry I forgot to reply: I don't see the value of doing so. If the code is expressive enough, extracting constants or global variables don't necessarily improve things. Besides, we have the `polling` struct, so I'd say that the values should be extracted there, as new fields. But again, unless we need different timeouts per environment – which isn't the case here – creating a new field in `polling` is not necessarily more expressive or clean than defining the timeout next to where it is going to be used.

2022-07-08 13:18 UTC, adejanovski commented on test/e2e/suite_test.go
> +	interval := 1 * time.Second
👌

2022-07-11 15:13 UTC, adejanovski approved these changes

2022-07-11 15:14 UTC, merged