Docs/cdc documentation
k8ssandra/k8ssandra-operator pull request #639
Opened 2022-07-28 07:28 UTC by Miles-Garnsey

**What this PR does**:

Adds CDC docs.

**Which issue(s) this PR fixes**:
#k8ssandra-1455

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2022-07-28 07:28 UTC, Miles-Garnsey commented
This needs to be tested as during the 1.2 release, `auth: false` started causing NPEs.

2022-07-28 07:29 UTC, Miles-Garnsey commented
@adejanovski I've put this ticket in the k8ssandra-operator repo. Not sure if you wanted it in k8ssandra instead.

2022-07-28 07:36 UTC, adejanovski requested changes
Small changes required, and then good to go 👍

2022-07-28 07:36 UTC, adejanovski commented on docs/enable-cdc.md
> +Next, you'll want to deploy a K8ssandraDatacenter with the Pulsar service's location referenced:
```suggestion
### Deploy a K8ssandraCluster

Next, you'll want to deploy a K8ssandraCluster with the Pulsar service's location referenced:
```

2022-07-28 07:36 UTC, adejanovski commented on docs/enable-cdc.md
> +When creating your tables, you'll need to do so with cdc=enabled as below:
```suggestion
### Create your tables with cdc enabled

When creating your tables, you'll need to do so with `cdc=true` as below:
```

2022-08-26 09:17 UTC, adejanovski approved these changes
This can be merged once the `K8ssandraDatacenter`  refs are replaced by `K8ssandraCluster` ones.
I'll port this over to the K8ssandra.io docs once it's done.

2022-08-26 09:17 UTC, adejanovski commented on docs/enable-cdc.md
> +Next, you'll want to deploy a K8ssandraDatacenter with the Pulsar service's location referenced:
```suggestion
### Deploy a K8ssandraCluster

Next, you'll want to deploy a K8ssandraCluster with the Pulsar service's location referenced:
```

2022-08-31 05:32 UTC, Miles-Garnsey commented
> This can be merged once the K8ssandraDatacenter  refs are replaced by K8ssandraCluster ones.
I'll port this over to the K8ssandra.io docs once it's done.

Is that true though, the particular part of the manifest we're talking about here is indeed the K8ssandraDatacenter (not the overall cluster). But then, we never really reference the term K8ssandraDatacenter in the YAML API do we... What do you think is clearer?

2022-08-31 07:21 UTC, adejanovski commented
> > This can be merged once the K8ssandraDatacenter  refs are replaced by K8ssandraCluster ones.
> > I'll port this over to the K8ssandra.io docs once it's done.
> 
> Is that true though, the particular part of the manifest we're talking about here is indeed the K8ssandraDatacenter (not the overall cluster). But then, we never really reference the term K8ssandraDatacenter in the YAML API do we... What do you think is clearer?

We don't have any object named a `K8ssandraDatacenter` AFAIK 🤔 We create `K8ssandraCluster` objects which will create `CassandraDatacenter` ones. So maybe you meant `CassandraDatacenter` instead?

2022-08-31 07:27 UTC, Miles-Garnsey commented
> We don't have any object named a K8ssandraDatacenter AFAIK thinking We create K8ssandraCluster objects which will create CassandraDatacenter ones. So maybe you meant CassandraDatacenter instead?

Right, that's true (and an ongoing gripe I have, but anyway...)

So should we say CassandraDatacenter or K8ssandraCluster then?

2022-08-31 07:31 UTC, adejanovski commented
> So should we say CassandraDatacenter or K8ssandraCluster then?

Since this documentation is for k8ssandra-operator I think it would be less confusing to go with `K8ssandraCluster`.

2022-08-31 16:05 UTC, Miles-Garnsey commented
All fixed (I think, some of these were a bit embarrassing) let me know if you're happy for me to merge.

I would like to test this against `main` however before merging, because keep in mind it hasn't been properly tested due to the auth bug.

2022-09-01 13:17 UTC, adejanovski approved these changes
Thanks for the updates 👍 

:shipit: 
![emoji-icon-glossy-05-06-travel-places-transport-water-u-boat-72dpi-forPersonalUseOnly (1)](https://user-images.githubusercontent.com/5096002/187923541-1d9c8dce-8400-4ad5-8dc4-3cac190087e4.png)

2022-09-08 09:49 UTC, Miles-Garnsey commented
Made one or two tiny changes having just re-tested again. All looking good.

2022-09-08 09:49 UTC, merged