Compute initial tokens for clusters with low number of tokens
k8ssandra/k8ssandra-operator pull request #743
Opened 2022-10-26 16:28 UTC by adutra

**What this PR does**:

This PR:

* Enhances the general-purpose mechanism introduced in #724 for applying any per-node configurations to Cassandra nodes;
* Introduces a new logic to compute and assign initial tokens to Cassandra nodes for clusters where num_tokens < 16, using the enhanced per-node configuration mechanism.

**Which issue(s) this PR fixes**:

Fixes #729 

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2022-11-03 11:10 UTC, adejanovski requested changes
Overall, the PR looks great.
I think the ReconcileMedusa function should be refactored to remove the redundant argument and the fixture for the new e2e test has a small error in dc2's rack affinity rules.
While testing, I ran into a problem with the per-node-config init container when a pod has no entry in the config map. It errors out with the following log message:

```
Error: bad file '/config/cassandra-env.sh': yaml: line 25: did not find expected <document start>
```

To trigger that problem, I initialized a cluster with 3 nodes and single token using Cassandra 4.0, then added a node which then doesn't get its token to be pre-computed.
Not sure what's causing this behavior as the container shouldn't enter the loop.
Here's the content of the config map:

```
data:
  test-dc1-rack1-sts-0_cassandra.yaml: |-

    initial_token: -9223372036854775808
  test-dc1-rack2-sts-0_cassandra.yaml: |-

    initial_token: -3074457345618258603
  test-dc1-rack3-sts-0_cassandra.yaml: |-

    initial_token: 3074457345618258602
```

The newly added node was `test-dc1-rack1-sts-1`.

2022-11-04 14:22 UTC, adutra commented on controllers/k8ssandra/cleanup.go
> +		if r.deletePerNodeConfigurations(ctx, kc, dcTemplate, namespace, remoteClient, logger) {
Unfortunately remote objects cannot rely on controller references for cleanup, so the cleanup must be manual. It's the same for Stargate, Reaper objects, etc.

2022-11-07 08:36 UTC, adutra commented on pkg/cassandra/tokens.go
> +		return
I can look into that, but this means passing a logger object around, which is something I tried to avoid so far. But I'll give it a try.

2022-11-07 13:42 UTC, jsanda commented on controllers/k8ssandra/cleanup.go
> +		if r.deletePerNodeConfigurations(ctx, kc, dcTemplate, namespace, remoteClient, logger) {
AFAIK ownership references can only be used for objects within the same namespace.

2022-11-07 13:56 UTC, adutra commented on pkg/cassandra/tokens.go
> +		return
Rather then passing a logger, I decided to return an error to the caller. Let me know if that works for you.

2022-11-07 16:16 UTC, adejanovski approved these changes
Awesome work, and some cool refactoring while you were at it 👍

2022-11-08 10:34 UTC, merged