874 crd docs update workflow
k8ssandra/k8ssandra-operator pull request #876
Opened 2023-02-13 13:42 UTC by RachanKaur

**What this PR does**: Poting the CRD update workflow 

**Which issue(s) this PR fixes**:
Fixes #874 

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2023-02-13 15:02 UTC, adejanovski requested changes
There are numerous references to the k8ssandra project which haven't been modified to match the fact that this is running against the k8ssandra-operator project.
Please do a cleanup and find a way to test this before we can review the PR.
You can do this by pushing changes in your own fork, where you'll get to invoke the workflow.

2023-02-13 15:02 UTC, adejanovski commented on .github/workflows/update-crd-reference.yaml
> +          mkdir -p ../k8ssandra/docs/content/en/reference/crd/k8ssandra-operator-crds-latest/ > /dev/null 2>&1
```suggestion
          mkdir -p docs/content/en/reference/crd/k8ssandra-operator-crds-latest/ > /dev/null 2>&1
```

2023-02-13 15:17 UTC, RachanKaur commented on .github/workflows/update-crd-reference.yaml
> +            mkdir -p ../k8ssandra/docs/content/en/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-$version > /dev/null 2>&1
do i need to change for cass-operator as well?

2023-02-13 15:33 UTC, RachanKaur commented on .github/workflows/update-crd-reference.yaml
> +            mkdir -p ../k8ssandra/docs/content/en/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-$version > /dev/null 2>&1
shouldn't that be /docs ?

2023-02-13 15:38 UTC, RachanKaur commented on .github/workflows/update-crd-reference.yaml
> +            mkdir -p ../k8ssandra/docs/content/en/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-$version > /dev/null 2>&1
I have updated all, testing if that works.

2023-02-17 16:41 UTC, adejanovski approved these changes

2023-02-20 10:37 UTC, merged